### ISSUE TITLE
Manually added rules should automatically populate the `message` field with associated identifiers

### ISSUE THREAD

**Issue by mlw** [northpolesec/santa#112]
When a rule is manually added via `santactl rule`, identifiers used to create the rule (such as path, signing ID, etc) should be automatically added into the `custommsg` column of the `rules` table. While not perfect (e.g., paths may not be descriptive and can change), it would generally help users identify source of rules when they're manually reviewed.

Created from discussion: #111

**Comment by russellhancox** [comment]
Copied from the discussion:

> This is a good idea, though overloading the message field is a bit weird. I think we should turn this into an Issue and add a new field to rules for free-form comments. When you add rules with santactl rule we can add a flag so you can provide a comment and if you don't, we'll make a reasonable default (from some combination of a signing ID or the original file path).
