### ISSUE TITLE
Updated ManagedPreferences not picked up by client

### ISSUE THREAD

**Issue by rorymurdock** [northpolesec/santa#118]
We updated the Santa config profile to change the `MachineOwner` attribute. Once the profile has been installed the owner remains the same in the preflight request, this continues until `santasyncservice` is restarted.

Slack ref: https://macadmins.slack.com/archives/C0E1VRBGW/p1731439617457319

**Comment by russellhancox** [comment]
Fixed with #121, which will be included in 2024.11
