### ISSUE TITLE
Enhancement: Add option to utilize LocalizedStrings with new UI

### ISSUE THREAD

**Issue by headmin** [northpolesec/santa#53]
As previously discussed with @pmarkowsky (taking a note here for reference), adding support for LocalizedStrings in the Santa UI would greatly enhance the user experience. While primarily a cosmetic feature, localization for languages like German, French, Swedish, and others is highly desirable.

**Comment by russellhancox** [comment]
The UI now supports localization and has translations for Russian, Ukrainian and German. Further localizations can be added (we'll very happily review PRs!) but there is no more "plumbing" left for this.
